name: Build and push Docker image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true
        default: 'tag'
      push:
        description: 'Push to container registry'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Validate push input
      run: |
        if [[ "${{ github.event.inputs.push }}" != "true" && "${{ github.event.inputs.push }}" != "false" ]]; then
          echo "Invalid value for push input. It must be either 'true' or 'false'."
          exit 1
        fi

    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@master
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@master
      with:
        context: .
        push: ${{ github.event.inputs.push }}
        tags: |
          jvrck/build-example:${{ github.event.inputs.tag }}
          ghcr.io/jvrck/build-example:${{ github.event.inputs.tag }}