name: Use latest release tag
on: [push]

jobs:
  
  get-latest-release:
    name: Get latest release
    uses: ./.github/workflows/rw_get_latest_release.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      # - name: Use latest release tag
      #   run: echo "Latest release tag is ${{ steps.latest_release.outputs.latest_release_tag }}"


#    ./.github/workflows/s/rw_get_latest_release.yml
