on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string
            push:
                required: true
                type: boolean
        secrets:
            DOCKER_USERNAME:
                required: true
            DOCKER_PASSWORD:
                required: true
            GH_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@master
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@master
    
        - name: Login to DockerHub
          uses: docker/login-action@master
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: Login to GitHub Container Registry
          uses: docker/login-action@master
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GH_TOKEN }}
    
        - name: Build and push Docker images
          uses: docker/build-push-action@master
          with:
            context: .
            push: ${{ inputs.push }}
            tags: ${{ inputs.tag }}